#!/bin/sh

g++ -std=c++23 aula.cpp disciplina.cpp main.cpp professores.cpp salas.cpp turmas.cpp -o ../bin/programa;
# $execute ; ../bin/programa < ../inputs/input_simples.txt
# $execute ; ../bin/programa < ../inputs/input_medio.txt
# $execute ; ../bin/programa < ../inputs/input_grande.txt
# $execute ; ../bin/programa < ../inputs/input_impossivel.txt
# $execute ; ../bin/programa
